const path = require('path');

module.exports = {
  name: 'iconism',
  begin: 0xe000,
  weight: 400,
  style: 'normal',
  metadata: 'made with iconism',
  url: null,
  selector: null,
  tag: null,
  prefix: 'i',
  width: 'auto',
  round: 1,
  templates: {
    css: path.join(__dirname, 'tpl', 'css.ejs'),
    font: path.join(__dirname, 'tpl', 'font.ejs'),
    scss: path.join(__dirname, 'tpl', 'scss.ejs'),
    sass: path.join(__dirname, 'tpl', 'sass.ejs'),
    less: path.join(__dirname, 'tpl', 'less.ejs'),
    html: path.join(__dirname, 'tpl', 'html.ejs'),
    json: path.join(__dirname, 'tpl', 'json.ejs'),
    sprite: path.join(__dirname, 'tpl', 'sprite.ejs'),
  },
  font: {
    names: {
      eot: '%name%',
      woff2: '%name%',
      woff: '%name%',
      ttf: '%name%',
      svg: '%name%',
    },
    exports: ['woff2', 'woff', 'ttf'],
  },
  asset: {
    names: {
      css: '%name%',
      scss: '%name%',
      sass: '%name%',
      less: '%name%',
      html: '%name%',
      json: '%name%',
      sprite: '%name%-defs',
    },
    exports: ['html', 'css'],
  },
  svgo: {
    plugins: [
      'cleanupAttrs',
      'removeDoctype',
      'removeXMLProcInst',
      'removeComments',
      'removeMetadata',
      'removeTitle',
      'removeDesc',
      'removeUselessDefs',
      'removeEditorsNSData',
      'removeEmptyAttrs',
      'removeHiddenElems',
      'removeEmptyText',
      'removeEmptyContainers',
      // removeViewBox,
      'cleanupEnableBackground',
      'convertStyleToAttrs',
      'convertColors',
      'convertPathData',
      'convertTransform',
      'removeUnknownsAndDefaults',
      'removeNonInheritableGroupAttrs',
      'removeUselessStrokeAndFill',
      'removeUnusedNS',
      'cleanupIDs',
      'cleanupNumericValues',
      'moveElemsAttrsToGroup',
      'moveGroupAttrsToElems',
      'collapseGroups',
      // removeRasterImages,
      { name: 'mergePaths', params: { force: true } },
      { name: 'convertShapeToPath', params: { convertArcs: true } },
      'sortAttrs',
      'removeDimensions',
      { name: 'removeAttrs', params: { attrs: '(stroke|fill)' } },
    ],
  },
};
